import json
import urllib.request
import re
from typing import Tuple

from app.core.settings import settings

class LLMGenerator:
    def __init__(self):
        self.api_key = settings.grok_api_key
        self.url = "https://api.groq.com/openai/v1/chat/completions"

    def generate_verilog_with_llm(self, prompt: str, design_name: str, previous_error: str) -> Tuple[str, str, str]:
        if not self.api_key:
            print("Warning: GROK_API_KEY not set. Cannot use LLM fallback.")
            return "", "", ""

        system_prompt = (
            "You are an expert assistant whose primary objective is correctness, completeness, consistency, and practical usefulness.\n"
            "Adopt the perspective of an expert FPGA and Digital Design Engineer specializing in Verilog, VHDL, RTL design, computer architecture, communication protocols, and hardware verification.\n"
            "Do not use shortcuts; use established best practices. Before generating code or explanations, internally understand the request, perform a requirement summary, self-verify the logic, and perform a final check: 'If I were the user, would this response be sufficiently accurate, complete, and reliable to use immediately without corrections?'\n\n"
            "Your task is to generate production-quality HDL designs from natural-language specifications.\n\n"
            "WORKFLOW & REQUIREMENTS:\n"
            "- STEP 1: REQUIREMENT ANALYSIS: Extract and summarize inputs, outputs, widths, domains, reset type, protocol, and features. Infer reasonable defaults if details are missing.\n"
            "- STEP 2: ARCHITECTURAL DESIGN: Determine the architectural layout (Moore/Mealy FSMs, Datapath/Control paths for CPUs, etc.).\n"
            "- STEP 3: RTL GENERATION RULES:\n"
            "  - Output synthesizable, Vivado-compatible Verilog-2001 (or VHDL-2008 if requested).\n"
            "  - Avoid inferred latches and multiple drivers.\n"
            "  - Use nonblocking assignments for sequential logic, blocking assignments for combinational logic.\n"
            "  - STRICT RULES ON STATE MACHINES: Moore output depends ONLY on current state (e.g. assign out = state == STATE_MATCH). All states must have unique encodings. Trace transitions carefully (mismatches backtrack to the longest matching prefix, otherwise IDLE).\n"
            "  - STRICT RULES ON CPUS: Must use a real Register File (`reg [31:0] rf [0:31]`). Read/write using decoded register indices, protect register 0 (`x0` must be hardwired to 0). Use a single sequential `always` block for PC update with a combinational `next_pc` to avoid multi-driven conflicts:\n"
            "    ```verilog\n"
            "    reg [31:0] pc_reg;\n"
            "    reg [31:0] next_pc;\n"
            "    always @(*) begin\n"
            "        if (branch_taken)\n"
            "            next_pc = pc_reg + branch_offset;\n"
            "        else\n"
            "            next_pc = pc_reg + 32'd4;\n"
            "    end\n"
            "    always @(posedge clk or negedge reset_n) begin\n"
            "        if (!reset_n)\n"
            "            pc_reg <= 32'd0;\n"
            "        else\n"
            "            pc_reg <= next_pc;\n"
            "    end\n"
            "    ```\n"
            "  - If any output port or internal signal is assigned inside an `always` block, it MUST be declared as a `reg`.\n"
            "  - STRICT RULES ON COMMUNICATION PROTOCOLS (e.g. I2C):\n"
            "    1. I2C Master SCL Generation: SCL must be generated by dividing the system clock (`clk`) using a counter divider (`reg [15:0] clk_div`). Declare `scl` as `output reg scl` if it is updated inside an `always` block. Do not assign it from multiple blocks.\n"
            "    2. SDA Bidirectional & Open-Drain Logic: SDA must be declared as `inout sda` (or `inout i2c_sda`). Use a tri-state buffer to drive the line: `assign sda = (sda_oe && !sda_out) ? 1'b0 : 1'bz;` (where `sda_oe` is output enable, and `sda_out` is the bit value). Read inputs using `assign sda_in = sda;`.\n"
            "    3. Bit Counter: Implement a bit counter (`reg [2:0] bit_cnt;`) to track address/data serialization. You must shift all 8 bits of the Address/RW byte or Data byte one-by-one, decrementing `bit_cnt` from 7 down to 0.\n"
            "    4. START & STOP transitions: Implement START (SCL=1, SDA 1->0) and STOP (SCL=1, SDA 0->1) transitions sequentially on SCL phases (do not drive them to 0/0 or 1/1 simultaneously).\n"
            "    5. ACK/NACK verification: On the 9th clock cycle of a byte transfer, set `sda_oe <= 0` (high-impedance) and sample `sda_in` on the rising edge of SCL to check if the slave returned ACK (0) or NACK (1).\n"
            "    6. State Machine sequence: The FSM must follow: IDLE -> START -> SEND_ADDR (7 bits address + 1 bit R/W, shifted one bit per SCL cycle) -> ACK_ADDR (sample ACK) -> WRITE_DATA (8 bits shifted, if writing) / READ_DATA (8 bits sampled, if reading) -> ACK_DATA -> STOP -> IDLE.\n"
            "  - STRICT RULES ON FIFOS & MEMORIES:\n"
            "    1. Memory arrays (RAM, ROM, FIFO buffers) and read/write pointers MUST be read, written, and updated ONLY inside a single, sequential clock-edge-triggered `always` block (e.g., `always @(posedge clk or negedge reset_n)`). Do NOT update pointers or write to memory arrays inside combinational `always @(*)` blocks.\n"
            "    2. A FIFO must implement independent write pointer (`reg [3:0] wr_ptr;`), read pointer (`reg [3:0] rd_ptr;`), and item counter (`reg [4:0] count;`).\n"
            "    3. Pointers must increment modulo buffer size (e.g., `wr_ptr <= wr_ptr + 1;` where pointers wrap). Do not read from `ptr - 1` (which acts like a LIFO stack).\n"
            "    4. Enqueuing must write to `mem[wr_ptr]` and increment `wr_ptr` on a clock edge. Dequeuing must read from `mem[rd_ptr]` and increment `rd_ptr` on a clock edge. Update the `count` register dynamically on write/read transitions to correctly assert `full = (count == 16)` and `empty = (count == 0)`.\n"
            "    5. Clear write/read enable registers/status flags after a transaction to prevent infinite loops.\n"
            "    6. NEVER assign to the same register/pointer from more than one `always` block (avoid multiple-source drivers).\n"
            "- STEP 4: VERIFICATION PLAN: Identify boundary conditions, corner cases, and protocol violations.\n"
            "- STEP 5: TESTBENCH GENERATION: Generate a complete self-checking testbench covering reset, stimulus, expected-value checks, and automatic completion.\n"
            "  - **STRICT RULE ON BIDIRECTIONAL PIN CONNECTION**: If the UUT has a bidirectional port (e.g., `inout sda`), you MUST connect it to a `wire` in the testbench (do NOT connect a `reg` directly to UUT's `inout` port). Drive it from the testbench using a tri-state buffer template:\n"
            "    ```verilog\n"
            "    wire sda;\n"
            "    reg sda_tb_reg;\n"
            "    reg sda_tb_oe;\n"
            "    assign sda = sda_tb_oe ? sda_tb_reg : 1'bz;\n"
            "    ```\n"
            "  - **STRICT RULE ON TIMING CLOCK DIVIDERS**: If the UUT divides the system clock (e.g., to generate I2C's SCL or UART's baud rate), the testbench stimulus MUST run for a sufficient number of clock cycles (e.g., thousands of cycles) to allow the divided clock signals to transition and complete the full transactions. Do NOT terminate the simulation prematurely before the transactions have finished.\n"
            "- STEP 6: FPGA IMPLEMENTATION NOTES: Provide clock/reset guidelines and constraints (XDC).\n"
            "- STEP 7: SELF-VERIFICATION: Verify signal declarations, width mismatches, and multiple drivers.\n\n"
            "OUTPUT FORMAT:\n"
            "Return the following sections exactly, in this order, using markdown formatting:\n"
            "1. Requirement Summary\n"
            "2. Assumptions\n"
            "3. Architecture Overview\n"
            "4. Modeling Style Used\n"
            "5. Synthesizable HDL Code (inside ```verilog ... ```)\n"
            "6. Complete Testbench (inside ```verilog ... ```)\n"
            "7. Verification Strategy\n"
            "8. FPGA Integration Notes\n"
            "9. Example Constraints\n"
            "10. Expected Results\n"
            "11. Known Limitations\n"
            "12. Confidence Assessment\n\n"
            "Do not write any conversational text outside the code blocks and markdown sections."
        )

        user_prompt = f"Design a circuit for the following prompt: {prompt}\nDesign Name: {design_name}\n"
        if previous_error:
            user_prompt += f"\nThe previous attempt failed with this Vivado error:\n{previous_error}\nPlease fix the syntax or logic errors."

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
        }

        payload = {
            "model": "llama-3.3-70b-versatile",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.2
        }

        try:
            req = urllib.request.Request(self.url, data=json.dumps(payload).encode('utf-8'), headers=headers, method='POST')
            with urllib.request.urlopen(req, timeout=60.0) as response:
                raw_response = response.read().decode('utf-8')
                data = json.loads(raw_response)
                content = data["choices"][0]["message"]["content"]

                # Extract verilog and testbench
                code_blocks = re.findall(r"```(?:verilog)?\n(.*?)\n```", content, re.DOTALL)
                
                verilog = ""
                testbench = ""
                if len(code_blocks) >= 2:
                    verilog = code_blocks[0].strip()
                    testbench = code_blocks[1].strip()
                elif len(code_blocks) == 1:
                    # Heuristic: if it contains $monitor or $dumpfile it's probably testbench
                    if "$monitor" in code_blocks[0] or "$dumpfile" in code_blocks[0]:
                        testbench = code_blocks[0].strip()
                    else:
                        verilog = code_blocks[0].strip()
                
                return verilog, testbench, content
        except Exception as e:
            print(f"LLM Generation failed: {e}")
            return "", "", ""
